### ISSUE TITLE
Drawer button not displaying (except in "/")

### ISSUE THREAD

**Issue by marymoser** [molecular-playground/frontend#11]
The hamburger button on the navbar (to open the sidebar) shows up on the landing page (route "/", file "index.html"), but not for any other page/routes. I checked the HTML and made sure that the links in the head tag, the header content, and scripts at the bottom are consistent.

**Comment by akaplo** [comment]
@marymoser is this still an issue? It looks like it's all good, but I just wanted to be sure, or else I'd help you out!

See below for a screenshot from `/locations`:

<img width="1440" alt="screen shot 2016-04-19 at 8 51 53 pm" src="https://cloud.githubusercontent.com/assets/7144148/14660136/ae28c2ee-0670-11e6-857b-13cee28e57b3.png">

**Comment by marymoser** [comment]
Sorry, this was a pretty old issue (before everything was "angularized" correctly!). Resolved now! :)
